* network_inventory

I started this project in order to have solution for keeping an
inventory over my various servers and other network equipment.

** Setup

1. Clone the repository
2. Create a virtual environment inside of the repository for example
   with:

#+BEGIN_EXAMPLE
python3 -m venv /path/to/repository
#+END_EXAMPLE

3. Cd into the repository and execute the setup.sh script. It will do
   some clean up tasks, install some python dependencies into the
   virtual environment, setup the database and a default user with the
   login ~admin~ and the password ~password~.
4. Afterwards you can run:

#+BEGIN_EXAMPLE
./manage.py runserver
#+END_EXAMPLE

   In order to run the developmenent server and access the application
   at http://localhost:8000

** Todos

*** TODO Setup an Ansible role

**** NEXT Create an Apache configuration

**** CANCELED move the database to mariadb
CLOSED: [2017-12-28 Thu 16:15]

- I had massive problems with mysqlclient and python3.5 and therefore
  dropped this. SQLite seems to work reasonably well.

**** NEXT setup a server

**** NEXT configure htaccess or something similar

*** NEXT extend the CSS

- A more centered layout would be nice
- Maybe some colours

*** NEXT include a RAID calculator

- https://thoughtworksnc.com/2017/08/30/writing-a-raid-calculator-in-python/

I would like to use this to show the usable space in a RAID system.

*** NEXT calculate the used space on a host

Means calculate the size all the VMs would use if they were thick.

*** NEXT Move the lists to their own page

- Since I have more devices than I thought it would provide a better
  overview than one big list.

*** DONE Create a list for all the cron jobs
CLOSED: [2017-12-27 Wed 16:45]

** Developemenet

For a detailed documentation of the source have a look at the
[[https://git.2li.ch/Nebucatnetzer/network_inventory/src/branch/master/docs/docs.org][documentation]].

