# Generated by Django 2.0 on 2017-12-22 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerDiskRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComputerRamRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_of_cores', models.IntegerField()),
                ('frequency', models.FloatField()),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Architecture')),
            ],
        ),
        migrations.CreateModel(
            name='CpuManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('command', models.CharField(max_length=50)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DiskSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_in_gb', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='')),
                ('valid_until', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Device')),
                ('hostname', models.CharField(max_length=20, unique=True)),
                ('ip', models.CharField(max_length=15)),
            ],
            bases=('inventory.device',),
        ),
        migrations.AddField(
            model_name='warranty',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Device'),
        ),
        migrations.AddField(
            model_name='ram',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.RamType'),
        ),
        migrations.AddField(
            model_name='disk',
            name='size_in_gb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.DiskSize'),
        ),
        migrations.AddField(
            model_name='disk',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.DiskType'),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Month'),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='weekday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Weekday'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.CpuManufacturer'),
        ),
        migrations.AddField(
            model_name='computerramrelation',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Ram'),
        ),
        migrations.AddField(
            model_name='computerdiskrelation',
            name='disk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Disk'),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Computer'),
        ),
        migrations.AddField(
            model_name='computerramrelation',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Computer'),
        ),
        migrations.AddField(
            model_name='computerdiskrelation',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Computer'),
        ),
        migrations.AddField(
            model_name='computer',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Cpu'),
        ),
        migrations.AddField(
            model_name='computer',
            name='disks',
            field=models.ManyToManyField(through='inventory.ComputerDiskRelation', to='inventory.Disk'),
        ),
        migrations.AddField(
            model_name='computer',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Computer'),
        ),
        migrations.AddField(
            model_name='computer',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.OperatingSystem'),
        ),
        migrations.AddField(
            model_name='computer',
            name='raid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Raid'),
        ),
        migrations.AddField(
            model_name='computer',
            name='ram',
            field=models.ManyToManyField(through='inventory.ComputerRamRelation', to='inventory.Ram'),
        ),
    ]
