on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master", "dev" ]
  workflow_dispatch:

env:
  IMAGE_NAME: network_inventory

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: networkinventory
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Test
        run: |
          nix flake check -L -j auto
